import { describe, expect, it } from 'vitest';
import { axisTuple, degreeLongitudeKm, from5186, parseCoordinate, presets, to5186, validateGeographic, within5186Area } from '../src/geo/coordinates';

// Independent reference values from system PROJ cs2cs, not generated by Proj4js.
// Command: cs2cs -f '%.9f' EPSG:4326 EPSG:5186
// PROJ authority input: latitude longitude; output: northing easting.
const references = [
  ['Seoul', 198056.366737027, 551885.030588716],
  ['Suwon', 202536.918902787, 518267.697275920],
  ['Daejeon', 234514.004263851, 416994.467255809],
  ['Jeju', 156437.519645526, 100758.481493640],
  ['Busan', 389076.803581329, 288993.755992737],
  ['Natural origin', 200000, 600000],
] as const;

describe('EPSG:4326 to EPSG:5186', () => {
  it.each(references)('agrees with PROJ at %s within 1 mm', (name, easting, northing) => {
    const result = to5186(presets[name]);
    expect(Math.abs(result.easting - easting)).toBeLessThan(.001);
    expect(Math.abs(result.northing - northing)).toBeLessThan(.001);
  });
  it.each(references)('converts the independent projected coordinate at %s back to the geographic point', (name, easting, northing) => {
    const result = from5186({ easting, northing });
    expect(result.longitude).toBeCloseTo(presets[name].longitude, 7);
    expect(result.latitude).toBeCloseTo(presets[name].latitude, 7);
  });
  it('warns about Busan while allowing a regional comparison', () => {
    expect(within5186Area(presets.Seoul)).toBe(true);
    expect(within5186Area(presets.Busan)).toBe(false);
    expect(() => to5186(presets.Busan)).not.toThrow();
  });
  it('rejects distant locations rather than presenting an unsuitable projection as valid', () => {
    expect(() => to5186({ longitude: 0, latitude: 0 })).toThrow('limited');
    expect(() => from5186({ easting: 1e20, northing: 1e20 })).toThrow();
  });
  it('distinguishes authority order from API order for both CRSs', () => {
    expect(axisTuple(presets.Seoul, true)).toEqual([37.5665, 126.978]);
    expect(axisTuple(presets.Seoul, false)).toEqual([126.978, 37.5665]);
    expect(axisTuple({ easting: 200000, northing: 600000 }, true)).toEqual([600000, 200000]);
    expect(axisTuple({ easting: 200000, northing: 600000 }, false)).toEqual([200000, 600000]);
  });
  it('rejects empty and non-finite coordinate inputs', () => {
    for (const value of ['', ' ', 'NaN', 'Infinity', 'hello']) expect(() => parseCoordinate(value)).toThrow();
    expect(parseCoordinate('-37.5')).toBe(-37.5);
    expect(() => validateGeographic({ longitude: 181, latitude: 0 })).toThrow('Longitude');
    expect(() => validateGeographic({ longitude: 0, latitude: 91 })).toThrow('Latitude');
    expect(() => validateGeographic({ longitude: NaN, latitude: 0 })).toThrow('finite');
  });
  it('uses the documented area-of-use bounds', () => {
    expect(within5186Area({ longitude: 126, latitude: 33.14 })).toBe(true);
    expect(within5186Area({ longitude: 128, latitude: 38.33 })).toBe(true);
    expect(within5186Area({ longitude: 125.999, latitude: 37 })).toBe(false);
    expect(within5186Area({ longitude: 127, latitude: 38.331 })).toBe(false);
  });
});

describe('longitude spacing illustration', () => {
  it('uses the WGS 84 ellipsoid parallel length and converges at the pole', () => {
    expect(degreeLongitudeKm(0)).toBeCloseTo(111.319491, 5);
    expect(degreeLongitudeKm(60)).toBeCloseTo(55.800002, 5);
    expect(degreeLongitudeKm(-60)).toBeCloseTo(degreeLongitudeKm(60), 8);
    expect(degreeLongitudeKm(90)).toBeLessThan(.000001);
  });
});
