export type VisualMode = 'globe' | 'projection' | 'map';
export type Step = { title: string; body: string; prompt: string; takeaway: string; detail: string; terms?: { term: string; meaning: string }[] };
export type Lesson = {
  id: string; name: string; short: string; mode: VisualMode; source: string; sourceName: string;
  steps: Step[]; quiz: { question: string; options: string[]; answer: number; explanation: string };
};

export const lessons: Lesson[] = [
  {
    id: 'foundations', name: 'CRS basics', short: 'Foundations', mode: 'globe',
    source: 'https://docs.qgis.org/3.44/en/docs/gentle_gis_introduction/coordinate_reference_systems.html', sourceName: 'QGIS · A gentle introduction to GIS',
    steps: [
      { title: 'A place is more than two numbers.', body: 'A pair like 37.5665 and 126.9780 describes a location only when we know what the numbers mean. Are they angles? Distances? Which comes first? A coordinate reference system gives coordinates that context.', prompt: 'Click the globe to choose a place. Follow its highlighted parallel and meridian to their intersection.', takeaway: 'Coordinates are values. A CRS tells us how to interpret them.', detail: 'To locate a place, we need to know what each number measures, its units, and where the measuring system is placed on Earth. Our example means 37.5665° north and 126.9780° east using WGS 84, a widely used global reference for positions. That identifies Seoul. The controls show the coordinates of whichever place you select.' },
      { title: 'Latitude tells us how far north.', body: 'Latitude is an angle north or south of the equator. The equator is 0°, the North Pole is +90°, and the South Pole is −90°. Lines of constant latitude are called parallels.', prompt: 'Move latitude through 0° and into negative values. Watch the green line move south of the equator and the angle change below.', takeaway: 'Latitude is an angle in degrees, not a distance in metres.', detail: 'In the round-Earth drawing, draw a line from Earth’s centre to the equator. Draw another from the centre to your point. The angle between the two lines is latitude. At the equator it is 0°; at the North Pole it is 90°. Points south of the equator get negative values. Earth is actually slightly flattened, so precise calculations use a line that sticks straight out of its surface. The ellipsoid lesson shows that difference.' },
      { title: 'Longitude tells us how far east.', body: 'Longitude measures an angle east or west of the prime meridian at Greenwich. East is positive and west is negative. Longitude meridians meet at the poles.', prompt: 'Move longitude east and west of 0°. Compare the orange meridian with Greenwich in the North Pole diagram.', takeaway: 'Longitude runs from −180° to +180°. Both ends meet at the antimeridian.', detail: 'Viewed from the North Pole, east longitude increases counterclockwise. All meridians meet at each pole, so longitude is not a unique direction there. Elsewhere, a longitude interval has a ground length that depends on latitude. Greenwich is the prime meridian in both CRSs used here; rotate the globe if it is on the far side.' },
      { title: 'First, give the Earth a reference.', body: 'Earth is not a perfect sphere, so we use a smooth, slightly flattened model called an ellipsoid. But a shape alone cannot tell us where a town is. We also need to agree how to line up our measuring system with the real Earth. That agreement is called a datum.', prompt: 'Toggle the flattened Earth model. Compare its shape with the round outline. Look at the line that sticks straight out from the selected point.', takeaway: 'The ellipsoid models the shape. The datum defines how our measuring system fits the real Earth.', detail: 'Imagine a survey station whose position has been carefully measured. Give it coordinates in the agreed system, and other survey teams can use it to check their measurements. Many such measured locations help put the system into practice; that is called a reference frame. The line that sticks straight out of the surface in the diagram is called the surface normal. On a flattened Earth, it usually does not point to the centre.', terms: [
        { term: 'Ellipsoid', meaning: 'A smooth mathematical model of Earth’s shape. It is slightly flattened at the poles.' },
        { term: 'Datum', meaning: 'The agreed Earth model and the rules for lining up our measuring system with the real Earth. A shape alone is not enough to locate a place.' },
        { term: 'Reference frame', meaning: 'The measuring system put into practice. Survey stations and other measured reference locations are given agreed coordinates, so other measurements can use the same system. In GIS, “datum” and “reference frame” are often used for closely related ideas.' },
        { term: 'Surface normal', meaning: 'A line that meets the surface at a right angle, like a pole standing straight up from the ground. On a perfectly round Earth this line also passes through the centre. On a flattened model it usually misses the centre.' },
      ] },
      { title: 'A curved surface. A flat map.', body: 'A map projection converts geographic positions into positions on a plane. It makes a flat map possible, but changes some combination of shape, area, distance, and direction.', prompt: 'Change the projection and compare the two companion views. The orange point represents the same place in both.', takeaway: 'A geographic CRS does not need a projection. A projected CRS does.', detail: 'The main view begins flat so you can compare projections immediately. The companion globe and map keep the same selected geographic point. These are D3 spherical illustrations, not the ellipsoidal EPSG:5186 calculation. A projected CRS requires its full definition, not just a flat-looking display.' },
      { title: 'That is a coordinate reference system.', body: 'A CRS makes coordinate values meaningful. Geographic systems use angular coordinates such as latitude and longitude. Projected systems add a map projection and usually express positions as easting and northing.', prompt: 'Select another place. Follow the CRS-component diagram to its named coordinates.', takeaway: 'Reference framework + axes + units, with a projection for a projected CRS.', detail: 'The component diagram uses WGS 84 as a geographic example. A projected CRS derives from a geographic reference framework and adds a projection conversion. CRSs may have two or three dimensions. EPSG:4326 and EPSG:5186 are both two-dimensional; neither code by itself defines an elevation axis.' },
    ],
    quiz: { question: 'What does a CRS add to a pair of coordinate numbers?', options: ['The context needed to locate them on Earth', 'An altitude for every point', 'A map without any distortion'], answer: 0, explanation: 'A CRS defines the reference framework, axes, and units needed to interpret coordinates. It does not automatically add height or remove distortion.' },
  },
  {
    id: 'projections', name: 'Projections', short: 'Projections', mode: 'projection',
    source: 'https://proj.org/en/stable/operations/projections/tmerc.html', sourceName: 'PROJ · Map projections',
    steps: [
      { title: 'Every flat map makes a trade-off.', body: 'Earth is curved, but a map is flat. Flattening Earth changes how some places look. The orange circles are the same size on a round Earth. Switch the map projection and watch some circles become larger or change shape. These changes are called distortion.', prompt: 'Choose Mercator and look at the circles near the top and bottom. Then choose Equal Earth and compare their size and shape.', takeaway: 'A flat map can change how large a place looks or what shape it has.', detail: 'In Mercator, circles far north or south look bigger than circles near the equator, even though they represent the same-sized areas on Earth. Equal Earth keeps those areas equal, but can stretch circles into other shapes. Equirectangular draws a simple rectangular grid and also changes shapes and sizes. None of these maps can keep every size, shape, and distance correct at once.' },
      { title: 'One degree is not a fixed distance.', body: 'Longitude lines meet at the poles, so they get closer together as you move north or south. A gap of 1° longitude covers about 111 km at the equator, but only about 56 km at 60° latitude.', prompt: 'Move latitude from 0° to 60°. Watch the orange 1° line and compare the lengths of the bars below.', takeaway: 'One degree does not always cover the same number of kilometres.', detail: 'This rectangular map gives longitude lines equal spacing on the screen. That does not mean they are equally far apart on Earth. The bars show the real-world length of 1° measured along a line of latitude. Near the poles, that length gets smaller. At a pole, all longitude lines meet at one point.' },
      { title: 'Choose a projection for your task.', body: 'Choose a map based on what you want to compare. To compare how much land countries cover, use a map that keeps their areas in the right proportion. To keep the angles where nearby lines meet, choose a map designed for that. No single flat map is best for every task.', prompt: 'Choose Compare areas or Local angles below. Look at how the circles change with each choice.', takeaway: 'Choose the map for what you need to measure.', detail: 'Compare areas chooses Equal Earth: the equal-sized circles keep equal areas on the map. Local angles chooses Mercator: angles between nearby lines are kept, but areas can look much larger. A 90° crossing is an example of an angle. Keeping angles does not guarantee correct sizes or distances. Even a map measured in metres can stretch distances, so careful distance measurement needs a suitable method for the region.' },
    ],
    quiz: { question: 'Which statement about map projections is true?', options: ['Metre units guarantee exact ground distances', 'A flat world map can preserve every property', 'Different projections preserve different properties'], answer: 2, explanation: 'Projection choice is a trade-off. Units alone do not establish measurement accuracy, and no flat world map preserves every property.' },
  },
  {
    id: 'epsg', name: 'EPSG:4326', short: 'EPSG:4326', mode: 'globe',
    source: 'https://epsg.io/4326', sourceName: 'EPSG dataset · WGS 84 / 4326',
    steps: [
      { title: 'A short code. A full definition.', body: 'An EPSG code is a short name for an agreed coordinate system. Software looks up the code to find out how to read the numbers. EPSG:4326 means WGS 84 latitude and longitude, measured in degrees. It saves us from writing out all those settings each time.', prompt: 'Look at the boxes below. Find the Earth reference, coordinate names, and units that EPSG:4326 selects.', takeaway: 'The code tells software which coordinate system the numbers use.', detail: 'If a file says EPSG:4326, its coordinates should be read as WGS 84 latitude and longitude in degrees. If it says EPSG:5186, the numbers should be read using a particular Korean grid in metres. Choosing the wrong code can put the data in the wrong place. Changing the label alone does not calculate new coordinates; we explore that in the coordinate lab.', terms: [
        { term: 'EPSG code', meaning: 'A number used to look up agreed settings. In these lessons, the codes name coordinate systems. The EPSG list also contains codes for other things, such as coordinate-conversion methods.' },
        { term: 'WGS 84', meaning: 'A widely used global reference for positions on Earth. EPSG:4326 uses it with latitude and longitude in degrees.' },
      ] },
      { title: 'EPSG:4326 is geographic WGS 84.', body: 'EPSG:4326 locates places worldwide using two angles: latitude tells us north or south, and longitude tells us east or west. Both are measured in degrees. The official EPSG definition puts latitude first, but many mapping programs put longitude first.', prompt: 'Toggle EPSG number order. Watch the green latitude value and orange longitude value switch places. The point stays where it is.', takeaway: 'Read the coordinate names. Do not assume the first number is always latitude.', detail: 'For Seoul, the latitude-first pair is 37.5665, 126.9780. A longitude-first program writes the same place as 126.9780, 37.5665. Both are correct when the program knows which order you are using. EPSG:4326 does not include height. It can be shown on a flat map, but the software chooses a projection to draw that picture separately.', terms: [
        { term: 'Number order / axis order', meaning: 'Which coordinate comes first in the pair. The official EPSG:4326 order is latitude, longitude. This app normally uses longitude, latitude.' },
        { term: 'Degrees', meaning: 'Units for an angle. A value such as 37.5° latitude is an angle north of the equator, not 37.5 metres.' },
      ] },
    ],
    quiz: { question: 'What units do latitude and longitude use in EPSG:4326?', options: ['Metres', 'Degrees', 'Pixels'], answer: 1, explanation: 'Latitude and longitude are angles measured in degrees. Metres measure distance; pixels describe positions on a screen.' },
  },
  {
    id: 'korea', name: 'EPSG:5186', short: 'EPSG:5186', mode: 'map',
    source: 'https://epsg.io/5186', sourceName: 'EPSG dataset · KGD2002 / Central Belt 2010',
    steps: [
      { title: 'A local grid for a local region.', body: 'EPSG:5186 describes places using a flat grid for part of South Korea. It uses metres instead of degrees. Easting gives the east–west position on the grid, and northing gives the north–south position. This grid is intended for land between 126°E and 128°E.', prompt: 'Choose Seoul, then Busan. See which point lies inside the shaded part of the map.', takeaway: 'EPSG:5186 is designed for a part of South Korea, not the whole world.', detail: 'The official name is KGD2002 / Central Belt 2010. Central Belt means the middle strip of South Korea shown by the box. The box also covers some sea, but the intended use is on land. The grid is made using a map projection called Transverse Mercator. The map outline here is simplified, so it does not show streets or property boundaries.', terms: [
        { term: 'Easting', meaning: 'Your east–west position on this grid, measured in metres. The number gets larger as you move east.' },
        { term: 'Northing', meaning: 'Your north–south position on this grid, measured in metres. The number gets larger as you move north.' },
        { term: 'KGD2002', meaning: 'The agreed Earth reference used by this Korean grid. Its full name is Korean Geodetic Datum 2002.' },
        { term: 'GRS 1980', meaning: 'The name of the slightly flattened Earth-shape model used by KGD2002.' },
        { term: 'Transverse Mercator', meaning: 'The name of the mathematical method used to turn positions on the curved Earth into this flat grid.' },
      ] },
      { title: 'The origin does not have to be zero.', body: 'This grid has a chosen starting point at 38°N, 127°E. You might expect its coordinates to be zero. Instead, the system adds 200,000 to easting and 600,000 to northing. Its starting point therefore reads E 200,000 m, N 600,000 m.', prompt: 'Start at Natural origin, then choose Seoul. Watch the orange and green guide lines. Toggle Include false offsets to see the added numbers.', takeaway: 'Adding a fixed number changes the coordinates, not the place.', detail: 'The orange guide shows the change in easting from the starting point; the green guide shows the change in northing. The Δ symbol means “difference”, so ΔE and ΔN are differences in those coordinate values. They are not exact ground-distance measurements. Turning off offsets changes only the explanation below; the map and coordinate fields keep using EPSG:5186.', terms: [
        { term: 'Natural origin', meaning: 'The chosen starting point for this map projection. Here it is 38° north, 127° east.' },
        { term: 'False easting / false northing', meaning: 'Fixed numbers added to the grid coordinates. Here they are 200,000 m for easting and 600,000 m for northing.' },
      ] },
      { title: 'Read the full definition.', body: 'A coordinate-system code includes more than its units. It also selects the Earth reference, map projection, starting point, and other settings. For EPSG:5186, the official number order is northing first, easting second. This app normally uses easting first.', prompt: 'Find the starting point and the line at 127°E. Toggle EPSG number order and watch the two coordinate values switch places.', takeaway: 'Use the names easting and northing to tell which number is which.', detail: 'The map does not turn when the number order changes: north is still up and east is still right. The official EPSG:5186 definition calls northing X and easting Y, so X does not always mean east. Similar codes can also use different settings. For example, EPSG:5181 adds 500,000 to northing, while EPSG:5186 adds 600,000. Those codes cannot simply replace each other.', terms: [
        { term: 'Central meridian', meaning: 'The middle longitude line of this projection, at 127°E. The projection is designed to work well near this line.' },
        { term: 'Scale factor 1', meaning: 'On the middle line, the projection does not enlarge or shrink distances on its Earth model. This does not make every distance on the map exact.' },
      ] },
    ],
    quiz: { question: 'At this grid’s starting point, what are easting and northing?', options: ['0 m and 0 m', '200,000 m and 600,000 m', '600,000 m and 200,000 m'], answer: 1, explanation: 'Easting is 200,000 m and northing is 600,000 m. If a program lists northing first, it writes the pair as 600000, 200000. The named values are still the same.' },
  },
  {
    id: 'lab', name: 'Coordinate lab', short: 'Coordinate lab', mode: 'map',
    source: 'https://epsg.io/15831', sourceName: 'EPSG dataset · KGD2002 to WGS 84 operation',
    steps: [
      { title: 'Change the numbers. Keep the place.', body: 'Select a place on the map, or enter coordinates in either CRS. The lab transforms the values while keeping the real location the same. Geographic degrees become projected metres.', prompt: 'Move the marker and follow the conversion diagram. Then enter projected coordinates to run the process in reverse.', takeaway: 'A transformation changes the coordinate description of a location.', detail: 'The pipeline first relates WGS 84 to KGD2002, then applies the Transverse Mercator conversion. It uses the approximate datum relation described by EPSG:15831, with about 1 m stated accuracy. The frame step can leave angular values unchanged at displayed precision, but it still has a distinct meaning. More decimal places do not imply survey accuracy.' },
      { title: 'Order matters as much as units.', body: 'Our map API expects longitude, latitude and easting, northing. The EPSG definitions specify the opposite order for these two CRSs. Both can represent the same point when interpreted correctly.', prompt: 'Toggle axis order. Compare both pairs of coloured fields and confirm that the map directions and location stay fixed.', takeaway: 'Use explicit field names at every library boundary.', detail: 'Proj4js uses longitude/latitude and easting/northing by default. OpenLayers uses conventional x/y coordinate arrays. The diagram tracks field identity separately from position. The lab stores named fields internally and adapts arrays explicitly; swapping values without changing their interpretation would be an error.' },
      { title: 'Assigning is not transforming.', body: 'Assigning a CRS changes how software interprets existing numbers. Transforming calculates new numbers that describe the same location in another CRS. Relabelling degrees as metres does not convert them.', prompt: 'Compare the teal correct location with the orange relabelled location. Try relabelling, then restore the original point.', takeaway: 'Assign the correct source CRS first. Then transform to the target CRS.', detail: 'Both interpretations are plotted so their different locations are visible. The dashed connector is a comparison, not a transformation path on Earth. In QGIS, changing the project CRS transforms the display without rewriting stored coordinates; reprojecting a layer creates new coordinates. This experiment intentionally interprets degree numbers as metres.' },
    ],
    quiz: { question: 'Your layer contains longitude/latitude degrees. What converts it to EPSG:5186?', options: ['Replace its CRS label with EPSG:5186', 'Swap the two columns only', 'Identify its source CRS and transform the coordinates'], answer: 2, explanation: 'A real transformation calculates projected metre coordinates from correctly identified geographic source coordinates. A new label alone leaves the original numbers unchanged.' },
  },
];

export const sources = [
  ['QGIS: Coordinate reference systems', 'Foundations, projection families, and practical exercises.', 'https://docs.qgis.org/3.44/en/docs/gentle_gis_introduction/coordinate_reference_systems.html'],
  ['EPSG:4326 · WGS 84', 'The geographic CRS definition, axes, and units.', 'https://epsg.io/4326'],
  ['EPSG:5186 · Central Belt 2010', 'Korea’s central-belt parameters and intended area.', 'https://epsg.io/5186'],
  ['EPSG:15831 · Datum transformation', 'The approximate KGD2002 to WGS 84 operation.', 'https://epsg.io/15831'],
  ['OSGeo Korea: Korean CRS guide', 'A Korean-language comparison of commonly used codes.', 'https://www.osgeo.kr/17'],
  ['QGIS tutorial: Working with projections', 'A practical guide by Ujaval Gandhi.', 'https://www.qgistutorials.com/en/docs/3/working_with_projections.html'],
  ['PROJ: Axis order', 'Why authority and software coordinate order can differ.', 'https://proj.org/en/stable/faq.html#why-is-the-axis-ordering-in-proj-not-consistent'],
  ['PROJ: Transverse Mercator', 'Parameters and mathematical background.', 'https://proj.org/en/stable/operations/projections/tmerc.html'],
  ['IOGP: EPSG guidance notes', 'The dataset, conversions, and WGS 84 accuracy.', 'https://epsg.org/guidance-notes.html'],
  ['Proj4js documentation', 'Browser transformations and API conventions.', 'https://proj4js.org/'],
];
export const videos = [
  ['Geographic and projected CRS', 'PSALM_GEO · English · Introduction', 'https://www.youtube.com/watch?v=GL833C2Gpn4'],
  ['Set a CRS in QGIS', '7StarTech · English · Practical', 'https://www.youtube.com/watch?v=bnxO0tO5UBc'],
  ['QGIS Cookbook: Coordinate systems', 'Kang Dong-jin · Korean · OSGeo Korea course', 'https://youtu.be/Ie3Dxek8jys'],
  ['Dynamic coordinate reference systems', 'IOGP · Advanced follow-up', 'https://www.youtube.com/playlist?list=PLt0-qTVCvEp1ZwKnf8iup320Cvp9AgXso'],
];
